version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18
    commands:
      - echo "Installing PHP version 8.2 ..."
      - phpenv global 8.2

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Additional pre-build commands if needed #cd $CODEBUILD_SRC_DIR/frontend && npm install && npm run build;

  build:
    commands:
      - if [ -e "$CODEBUILD_SRC_DIR/.!code-build" ]; then
        cd $CODEBUILD_SRC_DIR/backend && composer install;
        else
        echo ".!code-build not found. Skipping library installations.";
        fi

  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files: '**/*'
