version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 18
    commands:
      - echo "Installing PHP version 8.2 ..."
      - phpenv global 8.2
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Additional pre-build commands if needed
      - mv /var/www/html/backend/vendor /var/www/vendor_backup
      - mv /var/www/html/frontend/node_modules /var/www/node_modules_backup
  build:
    commands:
      #- ls -al $CODEBUILD_SRC_DIR  # List the contents of the source directory
      #- cd $CODEBUILD_SRC_DIR/backend # note: isntead, we do initial instalation of libraries manually and save the image and update stack config to use it
      #- composer install
      #- cd $CODEBUILD_SRC_DIR/frontend
      #- npm install
      #- npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: '**/*'
