version: '3.8'

services:
  frontend:
    image: node:14 # You can adjust the Node.js version if needed
    # Alternatively, use the official Node.js image with customization in local frontend/Dockerfile
    # build:
    #  context: ./frontend
    #  dockerfile: Dockerfile
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8080:8080"
    command: npm run serve

  backend:
    image: php:8.2-cli # Using PHP CLI image # You can adjust the PHP version if needed
    # Alternatively, use the official PHP image with customization from local backend/Dockerfile
    # build:
    #  context: ./backend
    #  dockerfile: Dockerfile
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
